spring:
  application:
    name: reserva-facil-laboratorios

  datasource:
    url: jdbc:postgresql://localhost:5432/reserva-facil-laboratorios
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creative: true
server:
  port: 8080