spring:
  application:
    name: reserva-facil-laboratorios

  datasource:
    url: jdbc:postgresql://pg-reserva-facil-lab.postgres.database.azure.com:5432/reserva-facil-lab
    username: ${RESERVA_LAB_USERNAME}
    password: ${RESERVA_LAB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creative: true
server:
  port: 8080